name: Unit tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Go test
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: "1.18.1"
      - name: Deploy devnet
        env:
          FORK_URL: ${{ secrets.FORK_URL }}
        run: make devnet-up
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - name: Build contracts
        run: cd testcases && forge build
      - name: Unit test
        run: make test
      - name: Acceptance tests
        run: make testacc
